version: '3'
services:
  flask_api:
    container_name: flask_api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
      - ../requirements.txt:/app/requirements.txt
    ports:
      - "5001:5001"
